<a href="https://colab.research.google.com/github/Patortiz26/IN6531-Miner-a-de-datos-2021-2/blob/main/Laboratorio7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1><center>Laboratorio 7: Aprendizaje Supervisado 🔮</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos</strong></center>

### Cuerpo Docente:

- Profesor: Pablo Badilla
- Auxiliar: Ignacio Meza D.
- Ayudante: Constanza Peña

### Equipo:

- Patricio Ortiz


### **Link de repositorio de GitHub:** `https://github.com/Patortiz26/Laboratorio-de-Programaci-n/`

## Temas a tratar

- Aprendizaje Supervisado
- Flujos de datos a través de `Pipelines`.

## Reglas

- Fecha de entrega: TBD
- **Grupos de 2 personas**
- **Ausentes** deberán realizar la actividad solos. 
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Prohibidas las copias. 
- Pueden usar cualquer matrial del curso que estimen conveniente.

## Objetivos principales del laboratorio

- Comprender el funcionamiento de clasificadores/regresores.
- Generar múltiples modelos predictivos.
- Comprender las ventajas de crear modelos en pipeline vs hacer las operaciones a mano.

El laboratorio deberá ser desarrollado sin el uso indiscriminado de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`, las cuales vale mencionar, son bastante más eficientes que los iteradores nativos sobre `DataFrames`.

#Importamos librerias utiles 😸

In [1]:
# Libreria Core del lab.
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split 

# Pre-procesamiento
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier

# Metricas de evaluación
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score

#Libreria para plotear
!pip install --upgrade plotly
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

# UMAP
# !pip install umap-learn

https://www.kaggle.com/antoinekrajnc/soccer-players-statistics

# 1. Predicciones Futboleras

<p align="center">
  <img src="https://drive.google.com/uc?export=view&id=1BnO4tyh3vM2P199Ec9s3JjngQ4qQ9seP"
" width="300">
</p>


Tras el trágico despido de la mítica mascota de Maipú, Renacín decide adentrarse como consultor en el mercado futbolero, el cuál (para variar...) está cargado en especulaciones. 

Como su principal tarea será asesorar a los directivos de los clubes sobre cuál jugador comprar y cuál no, Renacín desea generar modelos predictivos que evaluén distintas características de los jugadores; todo con el fin de tomar decisiones concretas basadas en los datos.

Sin embargo, su condición de corporeo le impidió tomar la versión anterior de MDS7202, por lo que este motivo Renacín contrata a su equipo para lograr su objetivo final. Dado que aún tiene fuertes vínculos con la dirección de deportes de la municipalidad, el corporeo le entrega base de datos con las estadísticas de cada jugador para que su equipo empieze a trabajar ya con un dataset listo para ser usado.


**Los Datos**

Para este laboratorio deberán trabajar con los csv `statsplayers.csv` y `salarios.pickle`, donde deberán aplicar algoritmos de de aprendizaje supervisado (clasificación y regresión) en base a características que describen de jugadores de futbol.

Para comenzar cargue el dataset señalado y a continuación vea el reporte **`Player_Stats_Report.html`** (adjunto en la carpeta del enunciado) que describe las características principales del `DataFrame`.

In [2]:
# Si usted está utilizando Colabolatory le puede ser útil este código para cargar los archivos.
try:
    from google.colab import drive
    drive.mount("/content/drive")
    path = '/content/drive/My Drive/Colab Notebooks/MDS7202 - Laboratorio de programación/Lab 7'
except: 
    print('Ignorando conexión drive-colab')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
df_players = pd.read_csv(path+'/stats_players.csv')
df_players

Name          Nationality  ... Penalties Volleys
0      Cristiano Ronaldo             Portugal  ...        85      88
1           Lionel Messi            Argentina  ...        74      85
2                 Neymar               Brazil  ...        81      83
3            Luis Suárez              Uruguay  ...        85      88
4           Manuel Neuer              Germany  ...        47      11
...                  ...                  ...  ...       ...     ...
17583        Adam Dunbar  Republic of Ireland  ...        15      12
17584       Dylan McGoey  Republic of Ireland  ...        16      12
17585    Tommy Ouldridge              England  ...        42      37
17586         Mark Foden             Scotland  ...        24      12
17587   Barry Richardson              England  ...        22      12

[17588 rows x 39 columns]

## 1.1 Predicción de Seleccionados Nacionales 

Como primera tarea, Renacín, intrigado por la posibilidad de saber qué tan reconocido es un jugador, le consulta a su equipo si es posible predecir si un jugador será o no seleccionado nacional a partir de sus estadísticas en el juego. 

<p align="center">
  <img src="https://thumbs.gfycat.com/ThornyFrankFoxhound-size_restricted.gif" width="500">
</p>

### 1.1.1 Generación de Labels para la Clasificación [Sin Puntaje]


Primero comience generando las labels para la clasificación. Para esto, trabaje sobre el atributo ```National_Position``` suponiendo que los valores nulos son jugadores no seleccionados para representar a su país. 

Hecho esto, ¿Cuantos ejemplos por cada clase se tienen? Comente lo que observa.



**Respuesta:**

In [4]:
#Los valores nan se leen como un float, por lo que preguntamos por el tipo del valor por cada fila y agregamos en base a eso
df_players['Label'] = ['Seleccionado' if type(x) == str else 'No seleccionado' for x in df_players.National_Position]
df_players['Label'] = df_players['Label'].astype("category")

#Conteo de valores label
df_players.Label.value_counts()

No seleccionado    16513
Seleccionado        1075
Name: Label, dtype: int64

Se observa que la data contiene mayoritariamente jugadores que no han sido seleccionados a su selección nacional, lo que significa que estamos ante un problema desbalanceado.

### 1.1.2 Camino a la clasificación [1 punto]

<!-- <p align="center">
  <img src="http://vignette3.wikia.nocookie.net/inciclopedia/images/c/cd/Patada_Medel_Messi.gif/revision/latest?cb=20150705215005" width="500">
</p> -->

Para preprocesar el dataset, genere un `ColumnTransformer` en donde especifique las transformaciones que hay que realizar para cada columna (por ejemplo StandarScaler, MinMaxScaler, OneHotEncoder, etc...) para que puedan ser utilizadas correctamente por el modelo predictivo y guardelo en algúna variable.

Luego, comente y justifique las transformaciones elegidas sobre cada una de las variables (para esto utilice el material ```Player_Stats_Report.html``` que viene en el zip del lab), al igual que las transformaciones aplicadas.

Hecho lo anterior, **defina al menos 3 pipelines para la clasificación**, en donde utilice el mismo ColumnTransformer definido anteriormente, pero que varie entre cada pipeline los clasificadores. 

Para seleccionar los clasificadores más adecuados, utilice la siguiente guía:

<p align="center">
  <img src="https://scikit-learn.org/stable/_static/ml_map.png" width="500">
</p>

<br/>

Con ella, comente y justifique cada una de las decisiones tomadas al momento de desarrollar su pipeline.

**To-Do:**

- [x] Genere un ```ColumnTransformer``` enfocado en preprocesar los datos.
- [x] Indicar y Justificar que preprocesamiento utiliza sobre cada columna.
- [x] Crear 3 ``pipelines`` con diferentes clasificadores.
- [x] Para seleccionar los clasificadores base sus decisiones en la siguiente [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html)
- [x] No entrenar los ``pipelines`` aún.

**Nota:** No es necesario entrenar los clasificadores aún.

**Respuesta:**

In [5]:
#COLUMN TRANSFORMER
#importamos librerías utiles
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler

#Definimos las columnas y el tipo de procesamiento que se realizará
numeric_features = ["Height", "Weight", "Age", "Ball_Control", "Dribbling", "Marking",
                    "Sliding_Tackle","Standing_Tackle", "Aggression", "Reactions", "Interceptions",
                    "Vision", "Composure", "Crossing", "Short_Pass", "Long_Pass", "Acceleration",
                    "Speed", "Stamina", "Strength", "Balance", "Agility", "Jumping", "Heading",
                    "Shot_Power", "Finishing", "Long_Shots", "Curve", "Freekick_Accuracy", "Penalties",
                    "Volleys"]
numeric_transformer = StandardScaler()

categorical_features = ["Nationality", "Preffered_Foot"]
categorical_transformer = OneHotEncoder(sparse=False, handle_unknown="ignore")

ordinal_features = ["Work_Rate", "Weak_foot", "Skill_Moves"]
ordinal_cat = [["Low / Low","Low / Medium","Low / High", "Medium / Low","Medium / Medium","Medium / High","High / Low","High / Medium","High / High"],
               [1,2,3,4,5],
               [1,2,3,4,5]]
ordinal_transformer = OrdinalEncoder(categories=ordinal_cat)

#Se crea el CT
preprocessor = ColumnTransformer(
    transformers=[
        ("numerical", numeric_transformer, numeric_features),
        ("categorical", categorical_transformer, categorical_features),
        ('ordinal', ordinal_transformer, ordinal_features)
    ]
)

* Las variables númericas se escalaron usando un `StandardScaler()` pues observando el documento adjunto se observó que la mayoría de las variables se distribuían de manera normal.

* Las variables categoricas fueron trabajadas usando `OneHotEncoder()` para crear las columnas de manera separada.

* Se separaron algunas variables ordinales para transformarlas con un `OrdinalEncoder()` para conservar la jerarquia entre dichas variables.

In [6]:
#CLASIFICADORES
#Importamos clasificadores
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

#Construimos los pipelines de clasificacion
clf_linear_svc = Pipeline(steps=[
                      ("preprocesamiento", preprocessor),
                      ("clasificador svc", SVC(kernel='linear'))
])

clf_knn = Pipeline(steps=[
                      ("preprocesamiento", preprocessor),
                      ("clasificador knn", KNeighborsClassifier(n_neighbors=3))
])

clf_random = Pipeline(steps=[
                      ("preprocesamiento", preprocessor),
                      ("clasificador random forest", RandomForestClassifier())
])

Siguiendo el flujo de trabajo propuesto en el enlace, al disponer de menos de 100 mil registros probaremos en primer lugar un `SVC()` utilizando `kernel=linear`. Posterior a ello, si el clasificador no funciona, se prueba con el `KNeighborsClassifier()`. De igual manera, en caso de que este no funcione se utiliza algún `EnsembleClassifier` por lo cual se decidió incorporar el `RandomForestClassifier()`

### 1.1.3 Entrenemos los pipelines [1 punto]

<p align="center">
  <img src="https://i.gifer.com/7Cc8.gif" width="350">
</p>


Ahora, entrene los `pipeline` generados en los pasos anteriores. Para esto, primero separe los datos de entrenamiento en un conjunto de entrenamiento y de prueba  (la proporción queda a su juicio).

En este paso, seleccione los ejemplos de forma aleatoria e intente mantener la distribución original de labels de cada clase en los conjuntos de prueba/entrenamiento. (vea la documentación de `train_test_split`).


Luego, entrene los pipelines

Una vez entrenado su modelo, evalue su rendimiento a través de diferentes métricas, comentando que significa cada uno de los valores obtenidos. Puede usar la función `classification_report` para corroborar sus resultados.

- ¿Qué implican los valores de accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional)?
- ¿Podrían mejorarse los resultados?, ¿Cómo?
- ¿Influye la cantidad de ejemplos por clase?

**To-Do**:

- [x] Separar el conjunto de datos en entrenamiento y de prueba.
- [x] Entrenar los `pipelines`.
- [x] Utilizar las métricas para evaluar los modelos generados.


**Respuesta:**

In [7]:
#Primero se separan los datos en train y test
features = df_players.drop(columns=['Name','Label','National_Position','Club_Position'])
labels = df_players.loc[:, "Label"]
X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.25, shuffle=True, stratify=labels, random_state=0
)

**Linear SVM**

In [8]:
#Ejecutamos clasificador
clf_linear_svc.fit(X_train,y_train)

#Predecimos
y_pred = clf_linear_svc.predict(X_test)

# Resultados
print("Matriz de confusión\n", confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

Matriz de confusión
 [[4114  232]
 [  14   37]]
                 precision    recall  f1-score   support

No seleccionado       1.00      0.95      0.97      4346
   Seleccionado       0.14      0.73      0.23        51

       accuracy                           0.94      4397
      macro avg       0.57      0.84      0.60      4397
   weighted avg       0.99      0.94      0.96      4397



Se observa que si bien el modelo pareciera presentar muy buenas métricas (todas sobre el 0.94) esto se debe a que predice a la mayoría de los jugadores como "no seleccionado". Lo anterior es un error en que se puede incurrir en un problema, pues como se vió previamente es un problema desbalanceado.

**KNN**

In [9]:
#Ejecutamos clasificador
clf_knn.fit(X_train,y_train)

#Predecimos
y_pred = clf_knn.predict(X_test)

#Resultados
print("Matriz de confusión\n", confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

Matriz de confusión
 [[4068  233]
 [  60   36]]
                 precision    recall  f1-score   support

No seleccionado       0.99      0.95      0.97      4301
   Seleccionado       0.13      0.38      0.20        96

       accuracy                           0.93      4397
      macro avg       0.56      0.66      0.58      4397
   weighted avg       0.97      0.93      0.95      4397



Se observa que el clasificador KNN mantiene la tónica del clasificador anterior, con el matiz de que este modelo empeora las métricas con respecto al anterior e inclusa empeora el número de aciertos en la clase positiva.

**RandomForest**

In [10]:
#Ejecutamos clasificador
clf_random.fit(X_train,y_train)

#Predecimos
y_pred = clf_random.predict(X_test)

#Resultados
print("Matriz de confusión\n", confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

Matriz de confusión
 [[4109  241]
 [  19   28]]
                 precision    recall  f1-score   support

No seleccionado       1.00      0.94      0.97      4350
   Seleccionado       0.10      0.60      0.18        47

       accuracy                           0.94      4397
      macro avg       0.55      0.77      0.57      4397
   weighted avg       0.99      0.94      0.96      4397



Vemos que este clasificador mantiene la tónica de los modelos anteriores, y sobrerepresenta a la clase "no seleccionado". Se debe notar que este modelo es el que peor clasifica para obtener a los jugadores seleccionados.

**Respuesta**:

Se observa en los tres clasificadores un comportamiento bastante similar en el cual se tienen métricas excelentes (en apariencia) pero que al observar el tipo de problema al que nos enfrentamos (problema desbalanceado) presenta un problema para predecir a los sujetos de la clase positiva (seleccionado).

Las métricas propiamente tal no tienen mucho margen de mejora (más allá de realizar un gridsearchCV), en cambio, tiene mucha posibilidad de mejorar sus pronósticos de la clase seleccionado. Para ello se deberían probar técnicas de oversampling o subsampling para permitir que el modelo mejore su capacidad predictiva en el conjunto menos representado en el dataset.

## 1.2 Predicción de posiciones de jugadores [2 puntos]

<p align="center">
  <img src="https://pbs.twimg.com/media/E1rfA1aWEAYU6Ny.jpg" width="500">
</p>

En una nueva jornada de desmesuradas transacciones deportivas, Renacín escuchó a sus colegas discutir acerca de que el precio de cada jugador depende en gran medida de la posición en la cancha en la que juega. Y además, que hay bastantes jugadores nuevos que no tienen muy claro en que posición verdaderamente brillarían, por lo que actualmente puede que actualmente estén jugando en posiciones sub-optimas. 

Viendo que los resultados del primer análisis no son tan esperanzadores, el corporeo los comanda a cambiar su tarea: ahora, les solicita que construyan un clasificador enfocado en predecir la mejor posición de los jugadores en la cancha según sus características. 

Para lograr esto, primero, les pide que etiqueten de la siguiente manera los valores que aparecen en el atributo ```Club_Position```, pidiendo que agrupen los valores en los siguientes grupos:

**Nota**:  Renacín les recalca que **no deben utilizar los valores ```Sub``` y ```Res``` de esta columna**.

```python
ataque = ['ST', 'CF'] 
central_ataque = ['RW', 'CAM', 'LW'] 
central = ['RM', 'CM', 'LM'] 
central_defensa = ['RWB', 'CDM', 'LWB']
defensa = ['RB', 'CB', 'LB']
arquero = ['GK']
```

Cabe señalar que al igual como lo realizado con la clasificación binaria, deberá justificar en base a la [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html) la elección del clasificador y se deben comentar los resultados obtenidos en la clasificación.

**To-Do**:

- [x] Aplique las etiquetas descritas anteriormente en cada uno de los valores señalados en esta sección.
- [x] Cuente cuantos por clase quedan.
- [x] Entrene el nuevo pipeline y ejecute una evaluación de este.  
- [x] Comente los resultados obtenidos.

**Respuesta:**

In [11]:
#reestructuramos, usando un diccionario
posiciones = {'ST':'ataque',             
              'RS':'ataque',       
              'CF':'ataque',           
              'LS':'ataque',     
              'RS':'ataque',             
              'LF':'ataque',       
              'RF':'ataque',                  
              'RW':'central_ataque',    
              'CAM':'central_ataque',     
              'LAM':'central_ataque',    
              'RAM':'central_ataque',        
              'LW':'central_ataque',        
              'RM':'central',       
              'CM':'central',       
              'RCM':'central',              
              'LCM':'central',                                                   
              'LM':'central',                                                   
              'LF':'central',              
              'RWB':'central_defensa',                                 
              'CDM':'central_defensa',                                
              'LDM':'central_defensa',                              
              'RDM':'central_defensa',           
              'LWB':'central_defensa',                     
              'RB':'defensa',                    
              'CB':'defensa',                              
              'LCB':'defensa',                              
              'RCB':'defensa', 
              'LB':'defensa',                
              'GK':'arquero',              
              'Sub':np.nan,  
              'Res':np.nan,  
              np.nan:np.nan}

df_players['Club_Position'] = [posiciones[x] for x in df_players.Club_Position]
df_players['Club_Position'] = df_players['Club_Position'].astype("category") #lectura como dato categorico
df_players = df_players.dropna(subset=['Club_Position']) #eliminar na's
df_players.Club_Position.value_counts() #Conteo de nuevas clases

defensa            2444
central            1626
ataque              853
central_defensa     741
central_ataque      653
arquero             632
Name: Club_Position, dtype: int64

In [12]:
#Primero se separan los datos en train y test
features = df_players.drop(columns=['Name','Label','National_Position','Club_Position'])
labels = df_players.loc[:, "Club_Position"]
X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.25, shuffle=True, stratify=labels, random_state=0
)

**Linear SVM**

In [13]:
#Ejecutamos clasificador
clf_linear_svc.fit(X_train,y_train)

#Predecimos
y_pred = clf_linear_svc.predict(X_test)

#Resultados
print("Matriz de confusión\n", confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

Matriz de confusión
 [[158   0   0   0   0   0]
 [  0 180  27  19   0   0]
 [  0  24 280  90  66  28]
 [  0  10  26  47   0   0]
 [  0   0  44   6  66  14]
 [  0   0  30   1  53 569]]
                 precision    recall  f1-score   support

        arquero       1.00      1.00      1.00       158
         ataque       0.84      0.80      0.82       226
        central       0.69      0.57      0.63       488
 central_ataque       0.29      0.57      0.38        83
central_defensa       0.36      0.51      0.42       130
        defensa       0.93      0.87      0.90       653

       accuracy                           0.75      1738
      macro avg       0.68      0.72      0.69      1738
   weighted avg       0.78      0.75      0.76      1738



Se observa que el modelo tiene una alta accuracy (75%) y logra predecir de buena manera a la mayoría de las clases presentes. Cabe destacar que este modelo identifica de manera perfecta a los arqueros. 

**KNN**

In [14]:
#Ejecutamos clasificador
clf_knn.fit(X_train,y_train)

#Predecimos
y_pred = clf_knn.predict(X_test)

#Resultados
print("Matriz de confusión\n", confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

Matriz de confusión
 [[158   0   0   0   0   0]
 [  0 172  56  40   3   1]
 [  0  28 233  70  77  42]
 [  0  13  44  44   3   4]
 [  0   1  35   6  62  20]
 [  0   0  39   3  40 544]]
                 precision    recall  f1-score   support

        arquero       1.00      1.00      1.00       158
         ataque       0.80      0.63      0.71       272
        central       0.57      0.52      0.54       450
 central_ataque       0.27      0.41      0.32       108
central_defensa       0.34      0.50      0.40       124
        defensa       0.89      0.87      0.88       626

       accuracy                           0.70      1738
      macro avg       0.65      0.65      0.64      1738
   weighted avg       0.73      0.70      0.71      1738



Se observa que este modelo tiene un peor accuracy que el caso previo(tiene 0.7), y al revisar en detalle se observa que el número de true positives disminuye en todas las categorias. Se destaca que nuevamente se logra diferenciar a todos los porteros de manera perfecta.

**Random Forest**

In [15]:
#Ejecutamos clasificador
clf_random.fit(X_train,y_train)

#Predecimos
y_pred = clf_random.predict(X_test)

#Resultados
print("Matriz de confusión\n", confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

Matriz de confusión
 [[158   0   0   0   0   0]
 [  0 189  21  17   0   0]
 [  0  18 286 105  68  27]
 [  0   7  28  36   0   0]
 [  0   0  31   2  49   5]
 [  0   0  41   3  68 579]]
                 precision    recall  f1-score   support

        arquero       1.00      1.00      1.00       158
         ataque       0.88      0.83      0.86       227
        central       0.70      0.57      0.63       504
 central_ataque       0.22      0.51      0.31        71
central_defensa       0.26      0.56      0.36        87
        defensa       0.95      0.84      0.89       691

       accuracy                           0.75      1738
      macro avg       0.67      0.72      0.67      1738
   weighted avg       0.81      0.75      0.77      1738



Se observa que si bien el modelo pareciera presenta métricas comparables l modelo inicial(ambos con accuracy 0.75)). Al mismo tiempo se observa que random forest logra identificar de mejor manera las clases "central-ataque" y "central_defensa" que son las dos categorías con menor presencia (omitiendo a los arqueros). Finalmente se destaca que todos los arqueros fueron correctamente asignados).

**Respuesta**:

Se observa que los modelos de random forest y support vector machines son los que presentan mejores métricas de desempeño. Siendo el random forest el que mejor predecia las clases con menos representación en el dataset. Además se debe destacar que todos los modelos (incluido KNN que fue el de peor rendimiento) identificaron perfectamente a los arqueros.

## 1.3 Predicción de Sueldos [2 puntos]

<p align="center">
  <img src="https://media.giphy.com/media/3oEjHWtHAFcOKS4iA0/giphy.gif" width="460">
</p>

Queriendo ahondar aún más en el mercado del balompíe, Renacin, logra obtener (de una manera no muy formal) los sueldos de múltiples futbolistas y los guarda en el archivo ```sueldos.csv```. Con ellos les solicita que generen un regresor que les permita predecir el sueldo de los futbolistas en base a las características de los pichichis, esto, debido a su motivación por invertir y/o realizar especulación sobre los sueldos de jugadores.

Renacin es claro señalando que deben seguir utilizando la [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html) y comenten cada uno de los pasos realizados, para obtener su regresión lineal. Señalándoles que no aceptara un $R^2$ inferior a 0.35 para el modelo solicitado.

Para esta parte usted tiene total libertad en la generación del regresor, la unica exigencia es que utilice un pipeline para generar la regresión y utilice la metrica $R^2$ para medir el rendimiento de esta.

**To-Do**:

- [x] Explique en que consiste la métrica $R^2$
- [X] Generar un pipeline para la regresión.
- [X] Obtener un regresor con un $R^2$ superior a  $0.35$.
- [ ] Comente sus resultados y si es posible mejorar los resultados obtenidos. ¿Se necesitarían más datos o otros tipos de características o una combinación de ambos?

**Respuesta**

$R^2$ es una métrica que nos permite evaluar el rendimiento de un modelo independiente de la escala en la estén los datos. Se calcula de la siguiente manera:

$$R^2 = 1 - \frac{MSE(model)}{MSE(baseline)}  $$

Donde MSE(baseline) es el Mean Square Error de un modelo "dummy" que predice el valor promedio para cada observación y MSE(model) es el Mean Square Error del modelo entrenado.

In [62]:
from sklearn.metrics import r2_score #metrica de desempeño
from sklearn.model_selection import GridSearchCV #buscador de hiper parametros

df_sueldos = pd.read_csv(path+'/salarios.csv') #lectura de nuevos datos
print(df_sueldos.columns) #Vemos las columnas del dataset
df = pd.merge(left = df_players, right = df_sueldos, #mezclamos ambos dataset para tener los sueldos por jugador
              left_on='Name', right_on='Player',
              how='inner')
print(f'La forma de la matriz es {df.shape}')

display(df.head())

Index(['Unnamed: 0', 'Player', 'Weekly Salary'], dtype='object')
La forma de la matriz es (987, 43)


Name Nationality  ...             Player Weekly Salary
0  Cristiano Ronaldo    Portugal  ...  Cristiano Ronaldo     1248536.0
1       Lionel Messi   Argentina  ...       Lionel Messi     1538905.0
2             Neymar      Brazil  ...             Neymar      797726.0
3        Luis Suárez     Uruguay  ...        Luis Suárez      508923.0
4       Manuel Neuer     Germany  ...       Manuel Neuer      326233.0

[5 rows x 43 columns]

In [51]:
#REGRESORES
#Importamos regresores
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor

#Construimos los pipelines de regresores, siguiendo flujo sugerido
rg_linear_svr = Pipeline(steps=[
                      ("preprocesamiento", preprocessor),
                      ("regresor svr linear", SVR(kernel='linear'))
])

rg_random = Pipeline(steps=[
                      ("preprocesamiento", preprocessor),
                      ("regresor random forest", RandomForestRegressor())
])

rg_rbf_svr = Pipeline(steps=[
                      ("preprocesamiento", preprocessor),
                      ("regresor svr rbf", SVR(kernel='rbf'))
])

In [41]:
#Primero se separan los datos en train y test
features = df.drop(columns=['Name', 'Label', 'National_Position', 
                                    'Club_Position','Unnamed: 0', 'Player'])
labels = df.loc[:, 'Weekly Salary']
X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.25, shuffle=True, random_state=0
)

**Linear SVM**

In [54]:
#Ejecutamos regresor
rg_linear_svr.fit(X_train,y_train)

#Predecimos
y_pred = rg_linear_svr.predict(X_test)

#Resultados
print(f'El R2 de este modelo es: {np.round(r2_score(y_test, y_pred),2)}')

EL R2 de este modelo es: -0.04


**Random Forest**

In [53]:
#Ejecutamos regresor
rg_random.fit(X_train,y_train)

#Predecimos
y_pred = rg_random.predict(X_test)

#Resultados
print(f'El R2 de este modelo es: {np.round(r2_score(y_test, y_pred),2)}')

EL R2 de este modelo es: 0.65


**SVM rbf**

In [59]:
#Ejecutamos el regresor
rg_rbf_svr.fit(X_train,y_train)

#Predecimos
y_pred = rg_rbf_svr.predict(X_test)

#Resultados
print(f'El R2 de este modelo es: {np.round(r2_score(y_test, y_pred),2)}')

EL R2 de este modelo es: -0.06


**Respuesta**:

Se observa que el modelo de random forest pudo superar la barrera solicitada de $R^2 > 0.35$ Mientras que los modelos de Support Vector Machines tenían un valor negativo. Para mejorar los resultados se podría optar por utilizar un GridSeachCV para obtener mejores combinaciones en los hiper parametros. Por otro lado, también se debe considerar que el número de observaciones se redujo considerablemente, por lo que convendría recolectar nuevos datos para validar los modelos entrenados.

# Conclusión
Eso ha sido todo para el lab de hoy, recuerden que el laboratorio tiene un plazo de entrega de una semana. Cualquier duda del laboratorio, no duden en contactarnos por mail o U-cursos.

<p align="center">
  <img src="https://media2.giphy.com/media/l1J3CbFgn5o7DGRuE/giphy.gif">
</p>

<br>
<center>
<img src="https://i.kym-cdn.com/photos/images/original/001/194/195/b18.png" width=100 height=50 />
</center>
<br>

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=87110296-876e-426f-b91d-aaf681223468' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>